version: "3.8"
services:
  # SQL Server Container
  mssql-container:
    container_name: mssql-container
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: Phuc1510@
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    # volumes:
    #   - ./BonheurDb.sql:/docker-entrypoint-initdb.d/BonheurDb.sql
    networks:
      - bonheur-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1433"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  # SQLPad Container
  sqlpad:
    container_name: sqlpad
    image: sqlpad/sqlpad
    ports:
      - "3000:3000"
    networks:
      - bonheur-network
    environment:
      SQLPAD_ADMIN: "admin"
      SQLPAD_ADMIN_PASSWORD: Phuc1510@
      SQLPAD_CONNECTIONS__mssql-container__name: "Bonheur SQL Server"
      SQLPAD_CONNECTIONS__mssql-container__driver: "sqlserver"
      SQLPAD_CONNECTIONS__mssql-container__host: "mssql-container"
      SQLPAD_CONNECTIONS__mssql-container__port: 1433
      SQLPAD_CONNECTIONS__mssql-container__username: "sa"
      SQLPAD_CONNECTIONS__mssql-container__password: "Phuc1510@"
      SQLPAD_CONNECTIONS__mssql-container__database: "master"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  # Bonheur Server Container
  bonheur-server-container:
    container_name: bonheur-server-container
    build:
      context: .
      dockerfile: DockerfileDotNet
    ports:
      - "8080:8080"
    depends_on:
      - mssql-container
    networks:
      - bonheur-network
    env_file:
      - Bonheur.API/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  bonheur-network:
    name: bonheur-network
    driver: bridge
#docker-compose -f ./docker-compose.yaml up -d mssql-container
#docker-compose -f ./docker-compose.yaml up -d sqlpad
#docker-compose -f ./docker-compose.yaml up -d bonheur-server-container
