name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Create .env file
        run: echo "${{ secrets.ENV_SECRET }}" > Bonheur.API/.env

      - name: Build and Push Docker image
        run: |
          docker-compose -f docker-compose.yaml build
          docker tag bonheurserver_bonheur-server-container ${{ secrets.DOCKER_USERNAME }}/bonheur-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bonheur-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to VPS using Password Authentication
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/bonheur-app:latest
            docker stop bonheur-app || true
            docker rm bonheur-app || true
            docker run -d --name bonheur-app \
              -p 8080:8080 \
              -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
              -e SMTP_HOST="${{ secrets.SMTP_HOST }}" \
              -e SMTP_PORT="${{ secrets.SMTP_PORT }}" \
              -e SMTP_USESSL="${{ secrets.SMTP_USESSL }}" \
              -e SMTP_NAME="${{ secrets.SMTP_NAME }}" \
              -e SMTP_USERNAME="${{ secrets.SMTP_USERNAME }}" \
              -e SMTP_EMAILADDRESS="${{ secrets.SMTP_EMAILADDRESS }}" \
              -e SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}" \
              -e EMAIL_CONFIRMATION_URL="${{ secrets.EMAIL_CONFIRMATION_URL }}" \
              -e EMAIL_RESET_PASSWORD_URL="${{ secrets.EMAIL_RESET_PASSWORD_URL }}" \
              -e EMAIL_CHANGE_EMAIL_URL="${{ secrets.EMAIL_CHANGE_EMAIL_URL }}" \
              -e AZURE_BLOB_CONNECTION_STRING="${{ secrets.AZURE_BLOB_CONNECTION_STRING }}" \
              -e AZURE_BLOB_CONTAINER_NAME="${{ secrets.AZURE_BLOB_CONTAINER_NAME }}" \
              -e AZURE_BLOB_URL="${{ secrets.AZURE_BLOB_URL }}" \
              -e AZURE_BLOB_KEY="${{ secrets.AZURE_BLOB_KEY }}" \
              -e DB_CONNECTION_STRING="${{ secrets.DB_CONNECTION_STRING }}" \
              -e PAYOS_CLIENT_ID="${{ secrets.PAYOS_CLIENT_ID }}" \
              -e PAYOS_API_KEY="${{ secrets.PAYOS_API_KEY }}" \
              -e PAYOS_CHECKSUM_KEY="${{ secrets.PAYOS_CHECKSUM_KEY }}" \
              -e PAYOS_WEBHOOK_URL="${{ secrets.PAYOS_WEBHOOK_URL }}" \
              -e PAYOS_PAYMENT_SUCCESS_URL="${{ secrets.PAYOS_PAYMENT_SUCCESS_URL }}" \
              -e PAYOS_PAYMENT_CANCEL_URL="${{ secrets.PAYOS_PAYMENT_CANCEL_URL }}" \
              -e GOONG_API_KEY="${{ secrets.GOONG_API_KEY }}" \
              -e RABBITMQ_HOST="${{ secrets.RABBITMQ_HOST }}" \
              -e RABBITMQ_USERNAME="${{ secrets.RABBITMQ_USERNAME }}" \
              -e RABBITMQ_PASSWORD="${{ secrets.RABBITMQ_PASSWORD }}" \
              ${{ secrets.DOCKER_USERNAME }}/bonheur-app:latest
          EOF
