# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production  # Chỉ định environment

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # Cài đặt Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Kiểm tra phiên bản Docker Compose đã được cài đặt

      # Đăng nhập Docker Hub bằng secrets
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
      # Tạo file .env từ GitHub Secrets
      - name: Create .env file
        run: echo "${{ secrets.ENV_SECRET }}" > Bonheur.API/.env

      # Build và push Docker image lên Docker Hub
      - name: Build and Push Docker image
        run: |
          docker-compose -f docker-compose.yaml build
          docker push ${{ secrets.DOCKER_USERNAME }}/bonheur-app:latest
